version: "3.0"

services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    container_name: kb
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  
  logstash:
    container_name: ls
    image: docker.elastic.co/logstash/logstash:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana

networks:
  elastic:
    driver: bridge